[IG]
ig = fsh-generated/resources/ImplementationGuide-de.medizininformatikinitiative.kerndatensatz.complete.json
; MII-KDS-Template (Interims-Form: GitHub-URL, wie in den Modul-Repos; Beschluss 2026-08-28)
template = https://github.com/medizininformatik-initiative/ig-template-mii-kds
